"""initial schema

Revision ID: 20260508_0001
Revises: 
Create Date: 2026-05-08 08:09:00.692318+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260508_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('cluster_id', sa.String(length=64), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=40), nullable=True),
    sa.Column('rule_id', sa.String(length=40), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_acknowledged'), 'alerts', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_cluster_id'), 'alerts', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_target_id'), 'alerts', ['target_id'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('external_operators',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('technical_contact', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('integration_type', sa.String(length=40), nullable=False),
    sa.Column('data_sharing_level', sa.String(length=24), nullable=False),
    sa.Column('masking_rules', sa.JSON(), nullable=True),
    sa.Column('auto_integrate', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.String(length=40), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_status', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_external_operators_status'), 'external_operators', ['status'], unique=False)
    op.create_table('le_agencies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('evaluation_mode', sa.String(length=24), nullable=False),
    sa.Column('schedule_interval', sa.String(length=40), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_triggers', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('false_positive_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_status'), 'rules', ['status'], unique=False)
    op.create_table('takedowns',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('initiated_by', sa.String(length=40), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('wallets_frozen', sa.Integer(), nullable=False),
    sa.Column('sims_flagged', sa.Integer(), nullable=False),
    sa.Column('agents_alerted', sa.Integer(), nullable=False),
    sa.Column('evidence_package_id', sa.String(length=80), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_takedowns_cluster_id'), 'takedowns', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_takedowns_status'), 'takedowns', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('operator_id', sa.String(length=40), nullable=True),
    sa.Column('key_hash', sa.String(length=80), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['external_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_operator_id'), 'api_keys', ['operator_id'], unique=False)
    op.create_table('le_cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agency_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cluster_ids', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_officer', sa.String(length=120), nullable=True),
    sa.Column('officer_contact', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['le_agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_le_cases_agency_id'), 'le_cases', ['agency_id'], unique=False)
    op.create_index(op.f('ix_le_cases_status'), 'le_cases', ['status'], unique=False)
    op.create_table('rule_triggers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('rule_id', sa.String(length=40), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=True),
    sa.Column('node_id', sa.String(length=80), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('actions_executed', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('overridden_by', sa.String(length=40), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_triggers_rule_id'), 'rule_triggers', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_triggers_triggered_at'), 'rule_triggers', ['triggered_at'], unique=False)
    op.create_table('shared_flags',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('operator_id', sa.String(length=40), nullable=False),
    sa.Column('identifier_type', sa.String(length=24), nullable=False),
    sa.Column('identifier_masked', sa.String(length=160), nullable=True),
    sa.Column('identifier_hash', sa.String(length=80), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['external_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_flags_direction'), 'shared_flags', ['direction'], unique=False)
    op.create_index(op.f('ix_shared_flags_operator_id'), 'shared_flags', ['operator_id'], unique=False)
    op.create_table('takedown_steps',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('takedown_id', sa.String(length=40), nullable=False),
    sa.Column('step_type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['takedown_id'], ['takedowns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_takedown_steps_takedown_id'), 'takedown_steps', ['takedown_id'], unique=False)
    op.create_table('evidence_packages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('takedown_id', sa.String(length=40), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['le_cases.id'], ),
    sa.ForeignKeyConstraint(['takedown_id'], ['takedowns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_packages_case_id'), 'evidence_packages', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_packages_cluster_id'), 'evidence_packages', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_evidence_packages_takedown_id'), 'evidence_packages', ['takedown_id'], unique=False)
    op.create_table('le_case_messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('sender_id', sa.String(length=40), nullable=False),
    sa.Column('sender_role', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['le_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_le_case_messages_case_id'), 'le_case_messages', ['case_id'], unique=False)
    op.create_table('le_outcomes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('outcome_type', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('amount_recovered', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['le_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_le_outcomes_case_id'), 'le_outcomes', ['case_id'], unique=False)
    op.create_table('evidence_access',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('package_id', sa.String(length=40), nullable=False),
    sa.Column('accessed_by', sa.String(length=40), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_role', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['evidence_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_access_package_id'), 'evidence_access', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_access_package_id'), table_name='evidence_access')
    op.drop_table('evidence_access')
    op.drop_index(op.f('ix_le_outcomes_case_id'), table_name='le_outcomes')
    op.drop_table('le_outcomes')
    op.drop_index(op.f('ix_le_case_messages_case_id'), table_name='le_case_messages')
    op.drop_table('le_case_messages')
    op.drop_index(op.f('ix_evidence_packages_takedown_id'), table_name='evidence_packages')
    op.drop_index(op.f('ix_evidence_packages_cluster_id'), table_name='evidence_packages')
    op.drop_index(op.f('ix_evidence_packages_case_id'), table_name='evidence_packages')
    op.drop_table('evidence_packages')
    op.drop_index(op.f('ix_takedown_steps_takedown_id'), table_name='takedown_steps')
    op.drop_table('takedown_steps')
    op.drop_index(op.f('ix_shared_flags_operator_id'), table_name='shared_flags')
    op.drop_index(op.f('ix_shared_flags_direction'), table_name='shared_flags')
    op.drop_table('shared_flags')
    op.drop_index(op.f('ix_rule_triggers_triggered_at'), table_name='rule_triggers')
    op.drop_index(op.f('ix_rule_triggers_rule_id'), table_name='rule_triggers')
    op.drop_table('rule_triggers')
    op.drop_index(op.f('ix_le_cases_status'), table_name='le_cases')
    op.drop_index(op.f('ix_le_cases_agency_id'), table_name='le_cases')
    op.drop_table('le_cases')
    op.drop_index(op.f('ix_api_keys_operator_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_index(op.f('ix_takedowns_status'), table_name='takedowns')
    op.drop_index(op.f('ix_takedowns_cluster_id'), table_name='takedowns')
    op.drop_table('takedowns')
    op.drop_index(op.f('ix_rules_status'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('le_agencies')
    op.drop_index(op.f('ix_external_operators_status'), table_name='external_operators')
    op.drop_table('external_operators')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_target_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_cluster_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
