"""totp fields on users

Revision ID: 959f0d12f96c
Revises: 20260508_0001
Create Date: 2026-05-08 08:30:06.712920+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "959f0d12f96c"
down_revision: str | None = "20260508_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("users", sa.Column("totp_secret", sa.String(length=255), nullable=True))
    # totp_enabled needs a server_default for existing rows; we drop the
    # default in a follow-up so new inserts must specify the value
    # (matches the model's default=False at the ORM layer).
    op.add_column(
        "users",
        sa.Column(
            "totp_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("users", "totp_enabled", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_enabled")
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
